name: basic
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - scikit-learn==0.20.1
  - statsmodels==0.9.0
  - spyder-kernels
  - pip:
    - PyYAML 
